### ISSUE TITLE
Fix superjson Dependency Error

### ISSUE THREAD

**Issue by alexfinnarn** [CUCentralAdvancement/cms#49]
https://github.com/blitz-js/babel-plugin-superjson-next/issues/43

That issue describes the problem. The solution is to either remove superjson and serialize/unserialize dates, or get this to work. I might just take it out quickly so that work on the Heroku build and deployment can continue.

**Acceptance Criteria**

- [ ] Remove superjson and babel dependencies
- [ ] Make sure to serialize and unserialize Prisma data before using
- [ ] ...or figure out how to make it work...

**Comment by Skn0tt** [comment]
See https://github.com/blitz-js/babel-plugin-superjson-next/issues/43#issuecomment-780156614
